# themes from https://github.com/alacritty/alacritty-theme

import = [ "~/.config/alacritty/themes/themes/dracula.toml"]

[font]
size = 18

[font.normal]
family = "Lilex Nerd Font"

[window]
decorations = "none"
opacity =  0.75
padding = { x = 5, y = 5 }
dynamic_padding = true

[selection]
save_to_clipboard = true
